#!/usr/bin/env python3.6
# -*- coding: utf-8 -*-

import textwrap
import stdlib
from stdlib.template import autotools
from stdlib.template.configure import configure
from stdlib.template.make import make
from stdlib.manifest import manifest


def patch_shadow():
    # Disable the installation of groups and its man pages, as coreutils provides a better one
    stdlib.cmd("sed -i 's/groups$(EXEEXT) //' src/Makefile.in")
    stdlib.cmd("find man -name Makefile.in -exec sed -i 's/groups\\.1 / /'   {} \\;")

    # Remove man pages installed by man-pages.
    stdlib.cmd("find man -name Makefile.in -exec sed -i 's/getspnam\\.3 / /' {} \\;")
    stdlib.cmd("find man -name Makefile.in -exec sed -i 's/passwd\\.5 / /'   {} \\;")

    # Encrypt the passwords using sha512
    stdlib.cmd("sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' etc/login.defs")

    # Change the obsolete /var/spool/mail to /var/mail.
    stdlib.cmd("sed -i -e 's@/var/spool/mail@/var/mail@' etc/login.defs")

    # Make the first user number generated by useradd 1000.
    stdlib.cmd("sed -i 's/1000/999/' etc/useradd")


@manifest(
    name='shadow',
    category='sys-apps',
    description='''
    An account management tool suite.
    ''',
    tags=['gnu', 'password', 'pam'],
    maintainer='grange_c@raven-os.org',
    licenses=[stdlib.license.License.BSD],
    upstream_url='https://github.com/shadow-maint/shadow',
    kind=stdlib.kind.Kind.EFFECTIVE,
    versions_data=[
        {
            'semver': '4.6.0',
            'fetch': [{
                    'url': 'https://github.com/shadow-maint/shadow/releases/download/4.6/shadow-4.6.tar.xz',
                    'sha256': '0998c8d84242a231ab0acb7f8613927ff5bcff095f8aa6b79478893a03f05583',
                },
            ],
        },
    ],
)
def build(build):
    packages = autotools.build(
        patch=patch_shadow,
        configure=lambda: configure(
            '--with-group-name-max-length=32',
        ),
    )

    # Packages member of `raven-os/essentials` should explicitly state all
    # of their dependencies, including indirect ones.
    packages['sys-apps/shadow'].rdepends_on('raven-os/corefs', '*')

    packages['sys-apps/shadow'].load_instructions('./instructions.sh')

    return packages
